### ISSUE TITLE
Comparison with is instead of == in TimeSeries.py

### ISSUE THREAD

**Issue by effjot** [DHI/ifm_contrib#5]
`import ifm_contrib as ifm` failed with „SyntaxWarning: "is" with a literal. Did you mean "=="?“ at line 180 of TimeSeries.py. The line is:

    if pattern is "equalMidPoints":

As far as i know, `is` compares identy of reference, not value, so either `"equalMidPoints"` should be a variable or the comparison in fact should be by `==`.
After changing to `==`, the import succeeded.

**Comment by red5alex** [comment]
Yes, that is right, thanks for the notification!

**Comment by effjot** [comment]
Thanks!
