### ISSUE TITLE
problem with _loadDocument function at __init__.py

### ISSUE THREAD

**Issue by borkial** [DHI/ifm_contrib#6]
Hi, 
I'm working with python 3.8.5.
When I tried to load a FeFlow document with the following code: 

_import ifm_contrib as ifm
file='file_name.dac'
doc=ifm.loadDocument(file)_

an error message appeared in the command line window, saying that the _ _loadDocument_ function hasn't been declared.

The problem was solved editing the __init__.py file.
In the line 59, where the ifm functions are loaded to the environment, I added the line: 

"from ifm38 import loadDocument as _loadDocument"

Seemly, for python's versions over 3.8, the main code didn't define the _loadDocument function. 

This change was made in my personal computer, so i didn't change the code here at GitHub. 
I think that the code's author should make any change within the original script.

Regards, 
SL.

**Comment by red5alex** [comment]
This has now been fixed. Thanks for the notification!
